---
title: "Why and how to use git with R Studio"
author: "rpubs.com/maurolepore/git"
output:
  ioslides_presentation:
    widescreen: false
---

```{r setup_slides, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = NA)
library(dplyr)
```

## Outline

### (Last update: `r Sys.time()`)

1. Curated resources and plans to learn git

2. Why and how to use git

3. Let's do it!

4. Explore git

Git and GitHub are two components of a system. I call both **git**.

This presentation focuses on users of R Studio. It bases on my personal experience and opinion.



# 1. Curated resources and plans to learn git

## Curated list of resources:

1. Learn WHY using git and gitHub:  [< 1h webinar](https://www.rstudio.com/resources/webinars/collaboration-and-time-travel-version-control-with-git-github-and-rstudio/)

2. Learn HOW to use git and gitHub: [< 1h webinar](https://www.rstudio.com/resources/webinars/rstudio-essentials-webinar-series-managing-part-2/)

3. Learn [common use of RStudio + git + gitHub](http://r-pkgs.had.co.nz/git.html)

4. Get quick help on both git and gitHub: [gitHub help](https://help.github.com/)

5. Learn git to the greatest possible detail: [book Pro Git](https://git-scm.com/book/en/v2)




# 2. Why and how to use git

## Why using git

- **to work more safely. **It heps you work more safely so you can take more risks (not using git is like free climbing)

- **to work more neatly. **It helps you to organise your work better by using consistent structure and procedure

- **to work more effectively. **it helps you achieve goals easier by focusing on compleating small incremental steps (particular tasks) towards that goal

- **To work more visibly. **it provides a website for your project

- **To work more collaboratively. **it provides a system for others to contribute to your work.


## How to use git

- **From RStudio.** R Studio interacts with git and gitHub simply--in a user-friendly way. The system is useful even for projects that do not use code or R. Only the most commonly used features of git are available from R Studio.

- **From a shell such as bash. **The shell lets you use the full power of git. For example, create tags and branches.

- **From a GUI. ** A list of software that provides a Graphical User Interphase for git is [here](https://git-scm.com/downloads/guis). GUIs likely let you use more of the functionality that git has than R Studio but less than the shell.


## Workflow


Simple workflow model adviced by github

- https://guides.github.com/introduction/flow/

- http://scottchacon.com/2011/08/31/github-flow.html

General models, including those not adviced by github

- https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow

# 3. Let's do it!

## Set up git

- Install git, open an account in gitHub, link git to RStudio.

See section *Git and GitHub / Initial set up* [here](http://r-pkgs.had.co.nz/git.html).



## Set up a project locally

- Create a new project in R Studio (all R packages are projects but not the opposite); check the box to use git.

### Optionaly

- Add some very basic components of the project.

- Make an initial commit changes in R Studio.


## Set up the project remotely, on gitHub

- Create a new repo in gitHub (https://github.com/new)

    + (MUST) name the project exactly the same as its local version,
    + `create repository`,
    + click the `copy to clipboard` button under `…or push an existing repository from the command line`. This is what you will be copying:

```
git remote add origin https://github.com/maurolepore/<newrepo>.git
git push -u origin master

```


## Set up the project remotely, from the shell

- Paste what you just copied in a shell at the directory of your local project. 

Open the shell from R Studio at `tools/shell`. You need internet connection. You will need to provide the shell with your login and password to acess gitHub.

Done! From now on, new commits (in your `master` branch) can be pushed to gitHub from the shell with `git push` or from RStudio clicking the green arrow.



# 4. Explore git and gitHub

## Some cool features to explore

- Explore what RStudio allows doing,

- Discuss the alternative state of files,

- Examine the history of commits,

- Examine diff in each file and line,

- Revert a file or line (before commiting it).

- Go to gitHub from RStudio

- Add new issues on gitHub and examine what you can do with it

- Including `Closes #<issue-number>` in a commit message closes an issue; or just refer to`#<issue number>`.

- Pull requests (related to branching and merging, which comes later).


## More power from the shell (or GUIs): tag

You can use tags to tag meaningful points along the history of the project so that later you can check out the project at those points very quickly.

Add (`-a`) a `tag` named `mytag` and add a message (`-m`) that says `"a silly tag"`:

```
git tag -a mytag -m "a silly tag"
```

Have a look at the history of the repository and note the new including tag.

You can check out (travel to) any tagged point in the history like this `git checkout mytag`. To go back to the master branch do `git checkout master`. Note how you move along the hisotry of the project.

## More power from the shell (or GUIs): branch

You can use branches to develop versions of your project that differ from the main branch (`master`). You can try risky things and if your change is  finally useful, you can merge it into the main branch. Otherwise you can simply discard the branch.

From R Studio you can check out any branch but RStudio does NOT provide the tools to create, merge or delete branches. You need to do it from the shell (tools/shell in RStudio).


## More power from the shell (or GUIs): add branch

To crate a new branch (`-b`) called `"newbranch"` do this: 

```
git checkout -b newbranch
```

To see all available branches do this:

```
git branch
```

Or, to see the history including branches do this (close the window when you are done):

```
gitk
```

## More power from the shell (or GUIs): merge branch

After one or more useful commits you can merge the branch into the master branch. First you need to move to the `master` branch and, from there, you merge the `newbranch`, like this:

```
git checkout master
git merge newbranch
```

`newbranch` is gone:

```
git branch
```



## More power from the shell (or GUIs): delete branch

If you no longer need the `newbranch` you can simply delete it (`-d`) with `git branch -d newbranch`. If the `newbranch` has not been merged into the `master` branch, say, because noting useful come out from it, you can remove it with this slightly different command: `git branch -D newbranch` (note it that `D` is capitalized).


## More headakes from the shell (or GUIs): merge conflict

With more poser come more problems. Merge conflics are common. If you want to start experimenting with branches, I strongly recommend you to read more about merge conflicts. For example see the section **Git and GitHub / Working with others** of [this book](http://r-pkgs.had.co.nz/git.html).

