---
title: "Tips for interviews"
author: "maurolepore@gmail.com"
date: "12 January 2017"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Prove your skills and personality

Your interviewers seek to answer two questions (\*):

1. Do you have the skills we need?
2. Can we put up with you? Or better: **do we like you?**

You most likely know how to prove 1. Here I **focus** on 2.

(\*) In other words, [Can we respect (1) and trust (2) you?](http://www.businessinsider.com/harvard-psychologist-amy-cuddy-how-people-judge-you-2016-1)

## Source of ideas

Books about connecting with people and persuading them:

-	[*Getting more*](https://gettingmore.com/)

-	*Convince them in 90 seconds* ([watch](https://www.youtube.com/watch?v=bUQ1WkjsxSY) from 1:35-4:00 sec)

## Outline

### ~~The application~~ (**IN DEVELOPMENT**)

~~Before you apply~~

~~When you apply~~

~~After you apply~~

### The interview

- Before you meet

- When you meet

- After you meet

# ~~The application~~ (**IN DEVELOPMENT**)

# The interview



## Before you meet: find connections

What connects you to them?

- friends, colleagues;

- institutions, communities;

- hobbies;

- life experiences (e.g. cities you lived, places you studied);

- something else?

Use e.g. Google, LinkedIn, twitter, Facebook

(It's OK to say you researched their professional life, not their personal life--do it but don't say you did it).

## Before you meet: find about yourself

What will they find about you if they look you up?

- I that what you want to show?

- Is there anything missing/inappropriate?

What will your personal references/people in common tell them?

- References written by a German or American may differ

- Their interpretation when they read such letters may differ

If you think you may need it, prepare a polite defense

## When you meet: dress for success

First impression counts more than anything: 

People judge if they like you or not in the first 2 seconds.


- Mix authority with approachability; look:

    - fresh, clean, up-to-date, approachable;
    
    - tidy, trustworthy, professional

Dress for your next job, not for the one you have!

## When you meet: pick useful attitudes

**Enthusiasm, curiosity and humility combine irresistibly!**  

Useful           |  Useless
----------------  |  -------
Enthusiastic      |  Anxious
Curious           |  Self-conscious
Confident         |  Arrogant
Relaxed           |  Bored
Patient           |  Impatient
...               |  ...
Match your attitude with appropriate tone of voice and gestures.  

## When you meet: focus on their needs

Consider the job offer they advertised. What do they need?

Match their needs one by one with the skills you have.

Demonstrate your skills with examples.

## When you meet: reduce percieved risk

A deal becomes more likely as its risk reduces.

What can you do to reduce the risk they face by hiring you?

Some (maybe crazy) ideas are these:

  - let them get to know you better,
  - prove skills based on past experience or a test,
  - provide personal/professional references,
  - be flexible to accept a casual contract,
  - lower the salary,
  - volunteer,

## When you meet: expand the cake

What else can you offer that makes the deal more likely?

(things not in the job description)

- Build capacity,

- mentor someone,

- do some management/administration,

- travel,

- do fieldwork?

## When you meet: note their eye colour

Look straight into their eye

(Deeply enough to note their eye color.)

Remember their name.

## When you meet: be a chamaleon

Do some small talk first, 

so you can find allies and common enemies, e.g.:

- The receptionist is so nice! 
- It is so hot today!)

### Neuro-Linguistic Programming (NLP)

Open your body; you hearth should point theirs

- don't cross arms, legs
- don't hold anything in your hands; show them openly

Mirror their tone of voice, gestures.

## When you meet: ask questions

Questions help you to better understand their needs.

They help you collect information useful to make a deal.

State less, ask more.

Compare:

- "Today is a nice day!"

- "Are you having a nice day today?"

## When you meet: focus on the person

They are first people, then interviewers.

_I suppose leadership at one time meant muscles; but today it means getting along with people._

-- Gandhi

## After the meeting: follow up. 

If you said you would do something, do it. 

Take from 1 to a few days to follow up. 

(One week maybe around the limit.)

Ask for feedback, learn, and do it better next time.

Whatever happens you are one interview closer to your next job

--

_There is no failure, only feedback_

--Nicholas Bootman (Convince them in 90 seconds)
